#!/bin/bash
source ./environment

echo creating secret

[ -e secrets.txt ] && rm secrets.txt

echo "export CACHE_GIT_URL=$CACHE_GIT_URL" >> secrets.txt
echo "export CACHE_ARCHIVE=$CACHE_ARCHIVE" >> secrets.txt
echo "export CACHE_BRANCH=$CACHE_BRANCH" >> secrets.txt


DOCKER_BUILDKIT=1 docker build -t $docker_tag -t $docker_latest \
    --secret id=secrets,src="$(pwd)/secrets.txt" \
    .
